title: Ethan Harris
author: Ethan Harris

github_username:  ethanwharris
linkedin_username:  ethanwharris

navigation:
- text: Home
  url: /
- text: Blog
  url: /blog.html

# Build settings
plugins:
  - jekyll-seo-tag
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
