compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  startings: [html, head, body]
  
sass:
  style: compressed

title: Ethan Harris
description: A blog relating to Deep Learning and all things Computer Science
url: https://ethanwharris.github.io
author: Ethan Harris

github_username:  ethanwharris
linkedin_username:  ethanwharris

navigation:
- text: Home
  url: /
- text: Blog
  url: /blog.html
  layout: post

plugins:
  - jekyll-seo-tag
  - jekyll-gist
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
